export const faqs=[
 {category:'College life',q:'How can I handle exam stress?',a:'Choose one assignment or exam topic. Break preparation into a short task and ask a tutor or professor for specific help. Campus Calm can help you plan a first step.',prompt:'I feel stressed about exams'},
 {category:'College life',q:'What can I do when I feel homesick?',a:'Try a familiar routine and a check-in with someone from home. A recurring campus activity can give you repeated chances to connect without needing a whole friend group immediately.',prompt:'I feel lonely and homesick on campus'},
 {category:'College life',q:'How do I balance school and a job?',a:'Map fixed commitments first. Choose a realistic priority for each day and protect breaks where possible. Talk with your supervisor or professor when responsibilities collide.',prompt:'I cannot balance my job and college'},
 {category:'College life',q:'How can I handle roommate conflict?',a:'Describe a specific behavior and make one clear request at a calm time. An RA or housing staff member may help mediate. Seek support if you feel threatened or unsafe.',prompt:'I am fighting with my roommate'},
 {category:'Well-being',q:'How can I start a better sleep routine?',a:'Choose a realistic wind-down time and a consistent routine. Reduce activities that keep you alert near bedtime. Persistent sleep problems deserve a conversation with a health professional.',prompt:'I cannot sleep at night'},
 {category:'Well-being',q:'When should I consider professional help?',a:'You can ask for help at any time. Seek professional support when distress is severe, worsening, persistent, or affecting daily life. You do not need to wait for a crisis.',prompt:'Should I talk to a counselor?'},
 {category:'Well-being',q:'Can this app diagnose me or recommend medicine?',a:'No. Campus Calm provides general wellness guidance. Only a qualified health professional can assess your situation and discuss diagnosis or treatment.',prompt:'Can you diagnose me?'},
 {category:'Getting help',q:'How do I contact campus counseling?',a:'Bowie State students can call Counseling Services at 301-860-4169 or email counselingservices@bowiestate.edu. Open Bowie State support for official service links. Ask about appointments and privacy policies.',prompt:'How can I contact campus counseling?'},
 {category:'Getting help',q:'What should I expect from a first appointment?',a:'A counselor may ask what brought you in, your current concerns, and what support you want. Ask them about confidentiality and its limits. You can bring notes and ask questions.',prompt:'What happens at a counseling appointment?'},
 {category:'Getting help',q:'What if I need urgent support?',a:'In the U.S., call or text 988 for crisis support or visit 988lifeline.org. Call 911 for immediate danger. Elsewhere, use your local emergency number and verified local crisis services.',prompt:''},
 {category:'Privacy and AI',q:'How does this AI chatbot work?',a:'A trained Naive Bayes language classifier estimates a wellness topic from your message. The server chooses curated guidance and uses recent chat context. This is a focused AI chatbot, not a generative language model or clinical assessment.',prompt:''},
 {category:'Privacy and AI',q:'Where are my messages and check-ins saved?',a:'Chat exists in this open tab and is sent to the app server for a response. The app does not intentionally store chat or send it to an external AI provider. Optional saved check-ins and plans remain in this browser. Hosting services may process operational metadata. This app is not a confidential medical service.',prompt:''},
 {category:'Privacy and AI',q:'Can I erase or download my saved data?',a:'Open Privacy & data to export saved check-ins and your plan or erase all local saved entries. Clear chat separately with New conversation. Other people using this browser may see saved entries.',prompt:''},

 {category:'Bowie State',q:'Is Bowie State counseling free for students?',a:'Bowie’s main Counseling Services page says counseling is free for enrolled students. Contact the office about your needs and appointment availability.',prompt:'How can I contact Bowie State counseling?'},
 {category:'Bowie State',q:'Where is the BSU Counseling Center and when is it open?',a:'The main service page lists Robinson Hall, Suite 2800 and Monday–Friday, 8 a.m.–5:30 p.m. Some older pages differ. Confirm the location and hours when booking.',prompt:''},
 {category:'Bowie State',q:'Who can I contact after hours at Bowie?',a:'Bowie lists 301-860-4164 for urgent or after-hours counseling support through ProtoCall. Public Safety is 301-860-4040. Call 911 for immediate danger, or call/text 988 for U.S. crisis support.',prompt:'What mental health support does Bowie have after hours?'},
 {category:'Bowie State',q:'Is there support specifically for Bowie freshmen?',a:'Counseling Services offers freshman interviews and peer support for adjusting to university life. The main page lists 301-860-4550 for freshman counseling. Ask the office which support fits your situation.',prompt:'I am a Bowie freshman and want help adjusting to college'},
 {category:'Bowie State',q:'Can I ask for accommodations related to a health condition?',a:'Contact Disability Support Services at 301-860-4085 or dss@bowiestate.edu to discuss documentation and the accommodation process. Approval depends on an individual review; this app cannot grant accommodations.',prompt:''},
 {category:'Bowie State',q:'Can I use distance counseling while outside Maryland?',a:'Bowie’s main counseling page requires students to be physically in Maryland for distance counseling. It describes a one-time consultation or local referral option for students outside the state. Ask Counseling Services about your circumstances.',prompt:''},

];
export const topics=['Exam pressure','Feeling lonely','Sleep trouble','Work and school','Money worries','Relationships'];
export const prompts=['I feel stressed about exams','I feel lonely on campus','I cannot sleep at night','I cannot balance my job and college','I am stressed about money','I am having relationship problems'];
export const moodLabels=['Very low','Low','Okay','Good','Great'];
export const groundSteps=[['5 things you can see','Look around and name five things. You can type them below.'],['4 things you can feel','Notice four comfortable textures or points of contact.'],['3 things you can hear','Listen for three sounds, nearby or in the distance.'],['2 things you can smell','Notice two scents, or think of two familiar ones.'],['1 thing you can taste','Notice one taste, or imagine a familiar taste.']];
