// Original, hand-authored examples. Each label has equal training weight.
export const corpus = {
 academics: ['I am stressed about exams and homework','My grades are falling and I failed a test','I have too many assignments due','I cannot focus on studying for finals','School deadlines are making me overwhelmed','I procrastinate on my coursework','I need help planning study time','I feel nervous before an exam','My professor expects too much work','I am struggling in my classes','I missed an exam and feel ashamed','My essay project and quiz are due tomorrow'],
 anxiety: ['I feel anxious and worried all day','My mind keeps racing with worry','I am panicking and need to calm down','I feel tense and cannot stop overthinking','I worry something bad will happen','My anxiety is overwhelming','I feel nervous for no reason','I have anxious thoughts at night','I need grounding for my panic','I am scared and uneasy','How do I cope with constant worry','I get butterflies when I meet new people'],
 loneliness: ['I feel lonely on campus','I miss home and my family','I have no friends at college','I feel isolated in my dorm','I do not fit in with other students','I want to meet people but feel alone','I am homesick and miss my old life','Everyone has friends except me','I feel disconnected from classmates','I eat alone and want company','I struggle to make new friends','Nobody invites me anywhere'],
 sleep: ['I cannot sleep at night','I stay awake until morning','My sleep schedule is messed up','I am tired because I slept badly','I keep scrolling instead of sleeping','I need a better bedtime routine','I wake up during the night','I feel exhausted after an all nighter','My roommate keeps me awake','I cannot fall asleep because my brain will not stop','I want to improve my rest','I sleep through my alarm'],
 burnout: ['I feel burned out from work and college','I cannot balance my job and school','I have no energy left for anything','I am exhausted and overwhelmed with responsibilities','My work shifts leave no time to relax','I feel drained and need a break','I have too much on my plate','I am doing everything but getting nowhere','I work late and have early classes','I need help setting boundaries with commitments','I feel guilty whenever I rest','I have lost my motivation'],
 money: ['I am stressed about money','I cannot afford tuition and rent','My financial aid has not arrived','I am worried about bills and debt','I need a college budget','I do not have enough money for groceries','I cannot pay my student fees','I worry about my paycheck','I need help with financial stress','My scholarship is not enough','I have trouble affording food','My housing payment is late'],
 relationships: ['I am fighting with my roommate','My relationship with my partner is stressful','My girlfriend and I keep arguing','My boyfriend does not listen','I need help with a friend conflict','I want to set boundaries in my relationship','My roommate ignores my needs','I just went through a breakup','How do I communicate with someone I care about','My family pressures me','I am dealing with a difficult friendship','I want to resolve conflict without arguing'],
 identity: ['I feel like an impostor in college','I doubt I deserve to be here','I keep comparing myself to other students','I feel pressure to prove myself','I am figuring out who I am','I feel judged because of my identity','I am struggling with self confidence','I want to feel comfortable being myself','I feel out of place as a first generation student','People make assumptions about my background','I feel like everyone is smarter than me','I feel insecure about my appearance'],
 lowmood: ['I have been feeling sad lately','I feel empty and down','I do not enjoy my hobbies anymore','I feel hopeless about my future','I cry a lot and feel low','I cannot get out of bed','I feel numb and disconnected','Nothing feels enjoyable anymore','I am feeling depressed','I have no motivation to do normal things','I feel worthless after every mistake','I feel miserable most days'],
 care: ['How do I find a therapist','Should I talk to a counselor','What happens at a counseling appointment','Can you diagnose me with depression','Do I need medication','I want professional mental health help','Is therapy confidential','How can I contact campus counseling','Can you replace a therapist','I need help finding a mental health professional','Is counseling expensive','What should I say in my first therapy session'],
 greeting: ['Hello how are you','Hi there','Hey I want to talk','Good morning','Thanks for listening','Thank you for helping me','I appreciate this conversation','Hey campus calm','Hello I need some support','Hi can we chat','Thank you that helped','Hey what can you do']
};
export const guidance = {
 academics: {label:'Academic stress', intro:'School pressure can make even a small task feel heavy.', steps:['Write down one deadline that matters most today.','Split that assignment into a ten-minute first step.','Ask your professor or tutoring center one specific question if you are stuck.'], question:'Which assignment or exam feels hardest right now?', action:'Make a study plan'},
 anxiety: {label:'Worry and anxiety', intro:'You do not have to solve every worry in this moment.', steps:['Put your feet on a comfortable surface and notice your surroundings.','Try a slow, comfortable breath without forcing it.','Name one thing you can influence today and one thing you can leave for later.'], question:'What was happening just before this feeling showed up?', action:'Try grounding'},
 loneliness: {label:'Belonging and homesickness', intro:'Feeling disconnected during college can be painful.', steps:['Choose one familiar person you could check in with.','Try a recurring campus activity where you can see the same people again.','Aim for one short conversation rather than an entire new friend group.'], question:'Are you missing people from home or finding it hard to connect on campus?', action:'Plan a connection'},
 sleep: {label:'Sleep and rest', intro:'Rest can be difficult when college life keeps your schedule unpredictable.', steps:['Choose a realistic wind-down time for tonight.','Put one demanding task aside before bedtime.','If sleep trouble persists or affects daily life, discuss it with a health professional.'], question:'Is falling asleep, staying asleep, or making time for sleep your biggest obstacle?', action:'Build a rest plan'},
 burnout: {label:'Work and college balance', intro:'You are carrying a lot. Your need for a break deserves attention.', steps:['List what must happen today and what can wait.','Protect a short break between classes and work if possible.','Consider one commitment you can renegotiate with a supervisor or professor.'], question:'Which part of your week leaves you most drained?', action:'Make a balance plan'},
 money: {label:'Financial stress', intro:'Money uncertainty can take up a lot of mental space.', steps:['Separate a payment deadline from an amount you do not yet know.','Contact financial aid or student support for verified options.','If food or housing is uncertain, ask about emergency aid and campus basic-needs services.'], question:'Is the most urgent issue a bill, a delayed payment, or everyday expenses?', action:'Plan one next step'},
 relationships: {label:'Relationships and boundaries', intro:'Conflict can feel especially intense when you share a dorm or depend on each other.', steps:['Describe one behavior and how it affects you without guessing someone’s motives.','Choose a calm moment and make one clear request.','If you feel threatened or unsafe, seek help from a trusted person or campus support.'], question:'What would you want the other person to understand about your needs?', action:'Write a boundary'},
 identity: {label:'Confidence and identity', intro:'Comparing your private struggles with someone else’s public success can be exhausting.', steps:['Name one specific effort you made recently.','Ask whether a harsh thought is a fact or an interpretation.','Look for a mentor or campus community where your experience feels understood.'], question:'What situation has been making you doubt yourself?', action:'Reflect in check-in'},
 lowmood: {label:'Low mood', intro:'Feeling low or disconnected deserves care and attention.', steps:['Choose a manageable basic need, such as a meal or getting out of your room.','Let someone you trust know how you have been feeling.','Reach out to a counselor if feelings persist, worsen, or interfere with daily life. You can ask for help sooner too.'], question:'How long has this been affecting you and what has daily life been like?', action:'Find support'},
 care: {label:'Professional support', intro:'Campus Calm offers general wellness guidance. It cannot diagnose conditions, prescribe treatment, or replace a counselor.', steps:['Look up your college’s official counseling or student health page.','Ask about appointments, costs, privacy, and urgent support.','Write down what you would like help with before your visit.'], question:'Would you like help preparing what to say when contacting a counselor?', action:'Find support'},
 greeting: {label:'Getting started', intro:'I’m here for a check-in. I can help you explore college stress and choose a small next step.', steps:[], question:'What has been on your mind today?', action:'Choose a topic'}
};
